# NumPy Arrays

https://numpy.org/doc/stable/reference/arrays.ndarray.html

In [52]:
import numpy as np

In [53]:
mylist = [1, 2, 3]
type(mylist)

list

To cast list type to a numpy array use `np.array()`:

In [54]:
myarray = np.array(mylist)
myarray

array([1, 2, 3])

In [55]:
type(myarray)

numpy.ndarray

Numpy arrays can have multiple dimensions (_ndarray_ = n-dimensional array).

How to create arrays? One way is to use `numpy.arange` (array range). `np.arange(a, b, s)` means create a sequence of integers from `a` to but not including `b` with step size `s`:

In [56]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`np.zeros()` creates a `numpy.ndarray` filled with zeros. `shape` argument is a tuple with first number denoting number of rows (the _height_ of the array) and second the number of columns (the _width_ of the array): 

In [58]:
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

NumPy by default creates `floats`, that's why we have `0.` above.

`np.ones()` creates a `numpy.ndarray` filled with ones (floats):

In [59]:
np.ones(shape=(3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

To create a sequence of pseudo-random number we first need to set a seed which guarantees that on each run we'll get the same sequence:

In [60]:
np.random.seed(101)

In [61]:
arr_rand1 = np.random.randint(5, 66, 7)
arr_rand1

array([36, 16, 22, 11, 28, 16, 52])

In [62]:
arr_rand2 = np.random.randint(5, 66, 7)
arr_rand2

array([14, 18, 45,  9, 45, 58, 65])

[ndarray.max()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html#numpy.ndarray.max) returns maximum along the specified axis. 

In [64]:
arr_rand1.max()

52

To get index location of the maximum value use [ndarray.argmax](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argmax.html#numpy.ndarray.argmax):

In [ ]:
arr_rand1.argmax()

`ndarray` offers similar functions for a minimum element:

In [ ]:
arr_rand1.min()

In [65]:
arr_rand1.argmin()

3